name: ci

on:
  push:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: build docker image
        run: "docker compose build"